name: 'Test Selenium IDE on Windows '

on:
  workflow_dispatch:
jobs:
  test:
    permissions:
      actions: read
      checks: read
      contents: write
      deployments: read
      issues: read
      discussions: read
      packages: read
      pages: read
      pull-requests: read
      repository-projects: read
      security-events: read
      statuses: read
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: winget install OpenJS.NodeJS.LTS
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm -r i
      - name: Build side-runner and selenium-ide
        run: pnpm run build
      - name: Run all tests
        run: pnpm run test
